<a href="https://colab.research.google.com/github/Yash-Yelave/Deep_Learning/blob/main/DL_PR3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Sigmoid activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Derivative of sigmoid
def sigmoid_derivative(x):
    return x * (1 - x)

# XOR dataset
X = np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
])

# Expected output
y = np.array([
    [0],
    [1],
    [1],
    [0]
])

np.random.seed(1)

# Initialize weights and biases
W1 = np.random.rand(2,2)
b1 = np.random.rand(1,2)

W2 = np.random.rand(2,1)
b2 = np.random.rand(1,1)

learning_rate = 0.5
epochs = 10000

print("Initial Weights and Biases")

print("W1:\n", W1)
print("b1:\n", b1)
print("W2:\n", W2)
print("b2:\n", b2)

for epoch in range(epochs):

    # Forward propagation
    hidden_input = np.dot(X, W1) + b1
    hidden_output = sigmoid(hidden_input)

    final_input = np.dot(hidden_output, W2) + b2
    predicted_output = sigmoid(final_input)

    # Error calculation
    error = y - predicted_output

    # Backpropagation
    d_output = error * sigmoid_derivative(predicted_output)

    error_hidden = d_output.dot(W2.T)
    d_hidden = error_hidden * sigmoid_derivative(hidden_output)

    # Update weights and biases
    W2 += hidden_output.T.dot(d_output) * learning_rate
    b2 += np.sum(d_output, axis=0, keepdims=True) * learning_rate

    W1 += X.T.dot(d_hidden) * learning_rate
    b1 += np.sum(d_hidden, axis=0, keepdims=True) * learning_rate


print("\nUpdated Weights and Biases After Training")

print("W1:\n", W1)
print("b1:\n", b1)
print("W2:\n", W2)
print("b2:\n", b2)

print("\nPredicted Output After Training")
print(predicted_output)

Initial Weights and Biases
W1:
 [[4.17022005e-01 7.20324493e-01]
 [1.14374817e-04 3.02332573e-01]]
b1:
 [[0.14675589 0.09233859]]
W2:
 [[0.18626021]
 [0.34556073]]
b2:
 [[0.39676747]]

Updated Weights and Biases After Training
W1:
 [[4.57240294 6.5037383 ]
 [4.56504161 6.47298548]]
b1:
 [[-7.01241151 -2.88530157]]
W2:
 [[-10.29421044]
 [  9.57897049]]
b2:
 [[-4.42471286]]

Predicted Output After Training
[[0.01931569]
 [0.98331818]
 [0.9833515 ]
 [0.01725879]]


In [2]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

X = np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
])

y = np.array([
    [0],
    [1],
    [1],
    [0]
])

np.random.seed(1)

W1 = np.random.rand(2,2)
b1 = np.random.rand(1,2)

W2 = np.random.rand(2,1)
b2 = np.random.rand(1,1)

# Save initial weights
initial_W1 = W1.copy()
initial_W2 = W2.copy()
initial_b1 = b1.copy()
initial_b2 = b2.copy()

learning_rate = 0.5
epochs = 10000

for i in range(epochs):

    hidden_input = np.dot(X, W1) + b1
    hidden_output = sigmoid(hidden_input)

    final_input = np.dot(hidden_output, W2) + b2
    predicted_output = sigmoid(final_input)

    error = y - predicted_output

    d_output = error * sigmoid_derivative(predicted_output)

    error_hidden = d_output.dot(W2.T)
    d_hidden = error_hidden * sigmoid_derivative(hidden_output)

    W2 += hidden_output.T.dot(d_output) * learning_rate
    b2 += np.sum(d_output, axis=0, keepdims=True) * learning_rate

    W1 += X.T.dot(d_hidden) * learning_rate
    b1 += np.sum(d_hidden, axis=0, keepdims=True) * learning_rate


print("\nInitial vs Updated Weights and Bias\n")

print("Parameter\tInitial Value\t\tUpdated Value")

for i in range(2):
    for j in range(2):
        print(f"W1({i+1},{j+1})\t\t{initial_W1[i][j]:.4f}\t\t\t{W1[i][j]:.4f}")

for i in range(2):
    print(f"b1({i+1})\t\t{initial_b1[0][i]:.4f}\t\t\t{b1[0][i]:.4f}")

for i in range(2):
    print(f"W2({i+1})\t\t{initial_W2[i][0]:.4f}\t\t\t{W2[i][0]:.4f}")

print(f"b2\t\t{initial_b2[0][0]:.4f}\t\t\t{b2[0][0]:.4f}")


print("\nFinal Output of Network\n")

print("Input1  Input2  Expected  Predicted")

for i in range(len(X)):
    print(f"{X[i][0]}       {X[i][1]}       {y[i][0]}        {predicted_output[i][0]:.4f}")


Initial vs Updated Weights and Bias

Parameter	Initial Value		Updated Value
W1(1,1)		0.4170			4.5724
W1(1,2)		0.7203			6.5037
W1(2,1)		0.0001			4.5650
W1(2,2)		0.3023			6.4730
b1(1)		0.1468			-7.0124
b1(2)		0.0923			-2.8853
W2(1)		0.1863			-10.2942
W2(2)		0.3456			9.5790
b2		0.3968			-4.4247

Final Output of Network

Input1  Input2  Expected  Predicted
0       0       0        0.0193
0       1       1        0.9833
1       0       1        0.9834
1       1       0        0.0173
